# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend application code
COPY . .
RUN python3 agent.py download-files

# EXPOSE 8081

# Command to run the LiveKit agent
CMD ["python", "agent.py", "dev"]
